# Generated by Django 5.0.6 on 2024-06-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontsetting',
            name='contact_us_footer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frontsetting',
            name='footer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frontsetting',
            name='phone_1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='frontsetting',
            name='phone_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='frontsetting',
            name='about_us_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
