# Generated by Django 5.0.6 on 2024-06-14 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_frontsetting_contact_us_footer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='core.skill', verbose_name='skills'),
        ),
        migrations.CreateModel(
            name='DuckerSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='social media title', max_length=500, null=True, verbose_name='title')),
                ('social_id', models.CharField(blank=True, help_text='social media id', max_length=500, null=True, verbose_name='social id')),
                ('link', models.CharField(blank=True, help_text='social media link', max_length=500, null=True, verbose_name='link')),
                ('svg', models.TextField(blank=True, help_text='svg for social media', null=True, verbose_name='svg')),
                ('order', models.PositiveSmallIntegerField(blank=True, default=1, help_text='this number is the position of icon on front', verbose_name='icon order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ducker_socials', to='core.profile', verbose_name='ducker socials')),
            ],
        ),
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='work title', max_length=200, null=True, verbose_name='work title')),
                ('company', models.CharField(blank=True, help_text='company', max_length=200, null=True, verbose_name='company')),
                ('start_date', models.DateField(blank=True, help_text='start date', null=True, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, help_text='end date', null=True, verbose_name='end date')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_history', to='core.profile', verbose_name='work history')),
            ],
        ),
    ]
