# Generated by Django 5.0.6 on 2024-06-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'آقا'), ('F', 'خانم')], default='m', max_length=1),
            preserve_default=False,
        ),
    ]
