# Generated by Django 5.0.6 on 2024-06-14 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile_gender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DuckerSocial',
            new_name='UsererSocial',
        ),
    ]
