# Generated by Django 5.0.6 on 2024-06-14 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_duckersocial_userersocial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsererSocial',
            new_name='UserSocial',
        ),
    ]
