# Generated by Django 5.0.6 on 2024-06-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_userersocial_usersocial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersocial',
            name='svg',
        ),
        migrations.AddField(
            model_name='usersocial',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='social_media/', verbose_name='logo'),
        ),
    ]
