# Generated by Django 5.0.6 on 2024-06-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_usersocial_svg_usersocial_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='social media title', max_length=500, null=True, verbose_name='title')),
                ('link', models.CharField(blank=True, help_text='social media link', max_length=500, null=True, verbose_name='link')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='social_media/', verbose_name='logo')),
                ('order', models.PositiveSmallIntegerField(blank=True, default=1, help_text='this number is the position of icon on front', verbose_name='icon order')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
