# Generated by Django 5.0.6 on 2024-06-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_svg_remove_socialmedia_logo_remove_usersocial_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='svg',
            name='svg',
            field=models.FileField(blank=True, null=True, upload_to='svgs'),
        ),
    ]
