# Generated by Django 5.0.6 on 2024-06-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_desc',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
